// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axbefmfkvnvqapqkavbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4YmVmbWZrdm52cWFwcWthdmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODE1NDUsImV4cCI6MjA2NDI1NzU0NX0.mU1q-0VaMQt_eqw2Gzr79tlO59jaBi1I5AskIUskhto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});